### ISSUE TITLE
Puppet run causes change in snmpd.conf forcing a service restart

### ISSUE THREAD

**Issue by jasonedwardsleadx** [example42/puppet-snmpd#8]
Hi,

We are using this module to pass in the snmpd.conf settings for all  our servers from common.yaml which works fine.

However the issue I’ve had since day 1 is, every time puppet runs it sees snmpd.conf as being different and changes the contents of the file again. This hasn't been an issue until I've gone live with some servers. The problem now is it causes a restart of the snmpd service which in turn generates a status flap error from our monitoring system on every puppet run. Creating unneeded noise for something which is otherwise working perfectly.

I think this is because of the way the template it is getting the key value pairs and putting them in the file. Related to an issue with the way Ruby 1.8 does hash ordering. But before I bin the idea of having this content in Hiera and go back to using a configuration file I thought I’d pick your brain as using a conf file defeats the object of splitting the data out into Hiera.

I've removed company specific CIDRs and strings with \<CIDR\>, \<company name\>, \<email@company.co.uk\>, \<pass\> and \<hostname\>

Let me know if you need anymore information.

**Content in common.yaml:**
 
> snmpd::options:
  'com2sec local localhost': '\<company name\>'
  'com2sec lx-backup-vlan \<CIDR\>': '\<company name\>'
  'com2sec prod-vpc \<CIDR\>': '\<company name\>'
  'com2sec lx-office \<CIDR\>': '\<company name\>'
  'com2sec dev-vpc \<CIDR\>': '\<company name\>'
  'access MyRWGroup ""': 'any noauth 0 all all all'
  'access MyROGroupOffice ""': 'any noauth 0 all none none'
  'access MyROGroupProd ""': 'any noauth 0 all none none'
  'access MyROGroupBackup ""': 'any noauth 0 all none none'
  'access MyROGroupDev ""': 'any noauth 0 all none none'
  'group MyRWGroup v2c': 'local'
  'group MyROGroupBackup v2c': 'lx-backup-vlan'
  'group MyROGroupDev v2c': 'dev-vpc'
  'group MyROGroupOffice v2c': 'lx-office'
  'group MyROGroupProd v2c': 'prod-vpc'
  'pass <pass>': '/usr/bin/perl /usr/local/bin/iostat.pl'
  'pass <pass>': '/usr/bin/ucd5820stat'
  'view all included  .1': '80'
 
**Content in snmpd.yaml in nat instance :**
 
>\#\#\# File managed with puppet \#\#\#
\#
\#\# Served by:        '\<puppet master FQDN\>'
\#\# Module:           'snmpd'
\#\# Template source:  'MODULES/snmpd/templates/snmpd.conf.erb'
\#
 
>sysName \<hostname\>
sysLocation \<company name\> dev Systems
sysContact \<email@companyname.co.uk\>
 
>\# The following is generated from snmpd::options
access MyROGroupProd "" any noauth 0 all none none
access MyROGroupBackup "" any noauth 0 all none none
group MyROGroupDev v2c dev-vpc
access MyROGroupOffice "" any noauth 0 all none none
group MyRWGroup v2c local
access MyRWGroup "" any noauth 0 all all all
com2sec prod-vpc \<CIDR\> \<company name\>
pass \<pass\> /usr/bin/perl /usr/local/bin/iostat.pl
group MyROGroupProd v2c prod-vpc
com2sec lx-backup-vlan \<CIDR\> \<company name\>
com2sec dev-vpc \<CIDR\> \<company name\>
pass <pass> /usr/bin/ucd5820stat
group MyROGroupOffice v2c lx-office
com2sec lx-office \<CIDR\> \<company name\>
view all included  .1 80
access MyROGroupDev "" any noauth 0 all none none
com2sec local localhost \<company name\>
group MyROGroupBackup v2c lx-backup-vlan
 
**Output from running puppet on nat-a.dev:**
 
> Notice: /Stage[main]/Snmpd/File[snmpd.conf]/content:
--- /etc/snmp/snmpd.conf        2015-01-13 09:53:00.637948115 +0000
+++ /tmp/puppet-file20150113-19039-1k7cpk2-0    2015-01-13 10:09:00.103674460 +0000
@@ -10,22 +10,22 @@
sysContact \<email@companyname.co.uk\>
 
> \# The following is generated from snmpd::options
-com2sec local localhost \<company name\>
-com2sec lx-backup-vlan \<CIDR\> \<company name\>
-access MyROGroupOffice "" any noauth 0 all none none
-com2sec dev-vpc \<CIDR\> \<company name\>
-pass \<pass\> /usr/bin/ucd5820stat
-group MyROGroupBackup v2c lx-backup-vlan
access MyROGroupProd "" any noauth 0 all none none
-com2sec lx-office \<CIDR\> \<company name\>
-group MyRWGroup v2c local
-group MyROGroupDev v2c dev-vpc
-group MyROGroupOffice v2c lx-office
access MyROGroupBackup "" any noauth 0 all none none
+group MyROGroupDev v2c dev-vpc
+access MyROGroupOffice "" any noauth 0 all none none
+group MyRWGroup v2c local
access MyRWGroup "" any noauth 0 all all all
com2sec prod-vpc \<CIDR\> \<company name\>
pass \<pass\> /usr/bin/perl /usr/local/bin/iostat.pl
group MyROGroupProd v2c prod-vpc
+com2sec lx-backup-vlan \<CIDR\> \<company name\>
+com2sec dev-vpc \<CIDR\> \<company name\>
+pass \<pass\> /usr/bin/ucd5820stat
+group MyROGroupOffice v2c lx-office
+com2sec lx-office \<CIDR\> \<company name\>
view all included  .1 80
access MyROGroupDev "" any noauth 0 all none none
+com2sec local localhost \<company name\>
+group MyROGroupBackup v2c lx-backup-vlan
 
 
> Info: Computing checksum on file /etc/snmp/snmpd.conf
Info: /Stage[main]/Snmpd/File[snmpd.conf]: Filebucketed /etc/snmp/snmpd.conf to
Notice: /Stage[main]/Snmpd/File[snmpd.conf]/content: content changed '{md5}d4099
Info: /Stage[main]/Snmpd/File[snmpd.conf]: Scheduling refresh of Service[snmpd]
Notice: /Stage[main]/Snmpd/Service[snmpd]: Triggered 'refresh' from 1 events

Can you help at all?

**Comment by alvagante** [comment]
It seems definitively due to hash ordering "randomness" in ruby 1.8 .
I'd provide a custom template and explicitly refer single hash keys inside there, ie:
[...]
com2sec local localhost <%= $options_hash['company name'] %>
[..]

**Comment by jasonedwardsleadx** [comment]
It looks to me that you can just change line 13 of snmpd.conf.erb 
From this:
`<% scope.lookupvar('snmpd::options').each_pair do |key, value| %><%= key %> <%= value %>`
To this:
`<% scope.lookupvar('snmpd::options').each do |key, value| %><%= key %> <%= value %>`

**Comment by alvagante** [comment]
Good, please make some test and if they are ok submit a PR.

**Comment by jasonedwardsleadx** [comment]
I've tested it and tweaked it slightly. The hash is now sorted alphabetically and doesn't change in subsequent puppet runs:

`<% scope.lookupvar('snmpd::options').sort.each do |option| %><%= option.first %> <%= option.last %>` I'll do some final testing and create a PR for you to take a look at.
